013 player implementation
ElysiumHSE/Elysium pull request #21
Opened 2023-05-02 12:18 UTC by MhlvDenis

https://github.com/ElysiumHSE/Elysium/issues/13 - ишью на реализацию плеера
https://github.com/ElysiumHSE/Elysium/issues/20 - текущие баги фронта, отложены до лучших времен

2023-05-11 18:46 UTC, devcrocod requested changes
* no logging
* no exception handling
* code looks good
* have arch questions
___
everything else is ok

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/.gitignore
> +/.idea
(

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/entities/Song.kt
> +    val mediaId: String = "",
null

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/remote/MusicDatabase.kt
> +    private val firestore = FirebaseFirestore.getInstance()
thread-safety?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/remote/MusicDatabase.kt
> +            emptyList()
handle exception

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/di/AppModule.kt
> +    @Singleton
It's incorrect to use a singleton annotation on a function, then apply it to class

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/FirebaseMusicSource.kt
> +        val allSongs = musicDatabase.getAllSongs()
It seems that this is not the best choice to load all tracks from db into memory

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/entities/Song.kt
> +data class Song(
why is each property string?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MusicNotificationManager.kt
> +        override fun getCurrentContentTitle(player: Player): CharSequence {
CharSequence?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MusicService.kt
> +    lateinit var dataSourceFactory: DefaultDataSource.Factory
do you know that lateinit is not updated after initialization? and what if you call to lateinit without checking, then an exception will be thrown?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/callbacks/MusicPlaybackPreparer.kt
> +    ) = false
it's weird

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/callbacks/MusicPlaybackPreparer.kt
> +        return PlaybackStateCompat.ACTION_PREPARE_FROM_MEDIA_ID or
What's going on here?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/other/Constants.kt
>      const val BASE_URL = "http://10.0.2.2:8080/elysium/"
For a link to the server, I would still advise putting it in properties file

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/ui/viewmodels/SongViewModel.kt
> +                    _curPlayerPosition.postValue(pos!!)
NPE?

2023-05-11 18:46 UTC, devcrocod commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/PlaybackStateCompatExt.kt
> +    get() = actions and PlaybackStateCompat.ACTION_PLAY != 0L ||
(

2023-05-12 19:46 UTC, fedorbondar commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MediaMetadataCompatExt.kt
> +            it.mediaId ?: "",
redundand check for null?

2023-05-12 19:49 UTC, fedorbondar commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MusicService.kt
> +                        result.sendResult(null)
might be a way to avoid null sending?

2023-05-12 19:51 UTC, fedorbondar commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/callbacks/MusicPlayerEventListener.kt
> +    @Deprecated("Deprecated in Java")
might be a way to avoid deprecated feature?

2023-05-14 15:30 UTC, FONARMEISTER commented
lgtm

2023-05-14 15:31 UTC, FONARMEISTER commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/FirebaseMusicSource.kt
> +    STATE_ERROR
Is this state reachable?

2023-05-14 15:31 UTC, FONARMEISTER commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/ui/fragments/HomeFragment.kt
> +import ru.hse.elysiumapp.R
What is it?

2023-05-18 11:23 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/di/AppModule.kt
> +    @Singleton
Это для dagger'a - библиотеки инжектов. В инжектах подставляются результаты функции, @Singleton ставиться для того, что бы результат функции создался один раз, и его дальше везде подставлять.

2023-05-18 11:27 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MusicService.kt
> +    lateinit var dataSourceFactory: DefaultDataSource.Factory
Здесь поле инициализируется инжектом, если ошибка произойдет, то во время создания включаемого объекта.

2023-05-18 11:32 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/ui/viewmodels/SongViewModel.kt
> +                    _curPlayerPosition.postValue(pos!!)
curPlayerPosition хранит Long, поэтому если pos == null, то в if не зайдем

2023-05-21 13:16 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/ui/fragments/HomeFragment.kt
> +import ru.hse.elysiumapp.R
Resolved

2023-05-21 13:16 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/FirebaseMusicSource.kt
> +    STATE_ERROR
Resolved

2023-05-21 14:12 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MusicService.kt
> +                        result.sendResult(null)
Здесь в результат отправляется содержимое массива, полученного из firestore. Т.к. данные в принципе не были получены, то используется не пустой массив, а null

2023-05-21 14:24 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/ui/viewmodels/SongViewModel.kt
> +                    _curPlayerPosition.postValue(pos!!)
Fixed

2023-05-21 14:26 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/remote/MusicDatabase.kt
> +            emptyList()
Добавил лог

2023-05-21 14:59 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/PlaybackStateCompatExt.kt
> +    get() = actions and PlaybackStateCompat.ACTION_PLAY != 0L ||
Посмотрел документацию PlaybackStateCompat, все через битмаски, более читаемого способа проверки нет

2023-05-21 15:22 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/entities/Song.kt
> +    val mediaId: String = "",
правим в 025

2023-05-21 15:23 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/entities/Song.kt
> +data class Song(
правим в 025

2023-05-21 15:23 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/MediaMetadataCompatExt.kt
> +            it.mediaId ?: "",
правим в 025

2023-05-21 15:25 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/data/remote/MusicDatabase.kt
> +    private val firestore = FirebaseFirestore.getInstance()
в 025 другую базу подключаем

2023-05-21 15:25 UTC, MhlvDenis commented on ElysiumApp/app/src/main/java/ru/hse/elysiumapp/exoplayer/FirebaseMusicSource.kt
> +        val allSongs = musicDatabase.getAllSongs()
заведу ишью на измененный алгоритм подгрузки

2023-05-21 18:10 UTC, FONARMEISTER commented
Very good code

2023-05-21 18:10 UTC, FONARMEISTER approved these changes

2023-05-28 13:05 UTC, merged